Repository AY1920S1-CS2103T-W11-1/main, pull requests merged in 2019-10, with the labels that each got.

#56 Fix add command section in UG
  docs/UserGuide.adoc
Labels: severity.Low, type.Bug

#61 Add more tests to sort
  docs/UserGuide.adoc
  src/main/java/seedu/algobase/logic/commands/SortCommand.java
  src/main/java/seedu/algobase/logic/parser/SortCommandParser.java
  src/test/java/seedu/algobase/logic/commands/CommandTestUtil.java
  src/test/java/seedu/algobase/logic/commands/SortCommandTest.java
  src/test/java/seedu/algobase/testutil/TypicalProblems.java
Labels: status.reviewRequired

#65 Plan(cannot add or edit tasks in plans)
  config/checkstyle/checkstyle.xml
  docs/UserGuide.adoc
  src/main/java/seedu/algobase/commons/core/Messages.java
  src/main/java/seedu/algobase/logic/commands/AddPlanCommand.java
  src/main/java/seedu/algobase/logic/commands/DeletePlanCommand.java
  src/main/java/seedu/algobase/logic/commands/EditPlanCommand.java
  src/main/java/seedu/algobase/logic/commands/FindPlanCommand.java
  src/main/java/seedu/algobase/logic/commands/ListPlanCommand.java
  src/main/java/seedu/algobase/logic/parser/AddPlanCommandParser.java
  src/main/java/seedu/algobase/logic/parser/AlgoBaseParser.java
  src/main/java/seedu/algobase/logic/parser/CliSyntax.java
  src/main/java/seedu/algobase/logic/parser/DeletePlanCommandParser.java
  src/main/java/seedu/algobase/logic/parser/EditPlanCommandParser.java
  src/main/java/seedu/algobase/logic/parser/FindPlanCommandParser.java
  src/main/java/seedu/algobase/logic/parser/ParserUtil.java
  src/main/java/seedu/algobase/model/AlgoBase.java
  src/main/java/seedu/algobase/model/Model.java
  src/main/java/seedu/algobase/model/ModelManager.java
  src/main/java/seedu/algobase/model/plan/NameContainsKeywordsPredicate.java
  src/main/java/seedu/algobase/model/plan/Plan.java
  src/main/java/seedu/algobase/model/plan/PlanDescription.java
  src/main/java/seedu/algobase/model/plan/PlanList.java
  src/main/java/seedu/algobase/model/plan/PlanName.java
  src/test/java/seedu/algobase/logic/commands/DefaultModelStub.java
Labels: status.reviewRequired

#64 Implement find for name, description and author
  docs/UserGuide.adoc
  src/main/java/seedu/algobase/commons/util/CollectionUtil.java
  src/main/java/seedu/algobase/logic/commands/FindCommand.java
  src/main/java/seedu/algobase/logic/parser/FindCommandParser.java
  src/main/java/seedu/algobase/model/problem/AuthorMatchesKeywordPredicate.java
  src/main/java/seedu/algobase/model/problem/DescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/algobase/model/problem/DifficultyIsInRangePredicate.java
  src/main/java/seedu/algobase/model/problem/NameContainsKeywordsPredicate.java
  src/main/java/seedu/algobase/model/problem/SourceMatchesKeywordPredicate.java
  src/main/java/seedu/algobase/model/problem/TagIncludesKeywordsPredicate.java
  src/test/java/seedu/algobase/logic/commands/FindCommandTest.java
  src/test/java/seedu/algobase/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/algobase/model/problem/AuthorMatchesKeywordPredicateTest.java
  src/test/java/seedu/algobase/model/problem/DescriptionContainsKeywordsPredicateTest.java
  src/test/java/seedu/algobase/model/problem/DifficultyIsInRangePredicateTest.java
  src/test/java/seedu/algobase/model/problem/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/algobase/model/problem/SourceMatchesKeywordPredicateTest.java
  src/test/java/seedu/algobase/model/problem/TagIncludesKeywordsPredicateTest.java
  src/test/java/seedu/algobase/testutil/TypicalProblems.java
Labels: status.reviewRequired

#66 Add switch command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/algobase/logic/Logic.java
  src/main/java/seedu/algobase/logic/LogicManager.java
  src/main/java/seedu/algobase/logic/commands/SwitchCommand.java
  src/main/java/seedu/algobase/logic/parser/AlgoBaseParser.java
  src/main/java/seedu/algobase/logic/parser/SwitchCommandParser.java
  src/main/java/seedu/algobase/model/GuiState.java
  src/main/java/seedu/algobase/model/Model.java
  src/main/java/seedu/algobase/model/ModelEnum.java
  src/main/java/seedu/algobase/model/ModelManager.java
  src/main/java/seedu/algobase/ui/DisplayTabPane.java
  src/main/java/seedu/algobase/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DisplayTab.fxml
  src/main/resources/view/DisplayTabPane.fxml
  src/test/java/seedu/algobase/logic/commands/DefaultModelStub.java
  src/test/java/seedu/algobase/logic/commands/SwitchCommandTest.java
  src/test/java/seedu/algobase/model/GuiStateTest.java
Labels: status.reviewRequired

#70 Add logics for deleting tasks and marking tasks as done/undone
  src/main/java/seedu/algobase/commons/core/Messages.java
  src/main/java/seedu/algobase/logic/commands/AddTaskCommand.java
  src/main/java/seedu/algobase/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/algobase/logic/commands/DoneTaskCommand.java
  src/main/java/seedu/algobase/logic/commands/UndoneTaskCommand.java
  src/main/java/seedu/algobase/logic/parser/AlgoBaseParser.java
  src/main/java/seedu/algobase/logic/parser/CliSyntax.java
  src/main/java/seedu/algobase/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/algobase/logic/parser/DoneTaskCommandParser.java
  src/main/java/seedu/algobase/logic/parser/UndoneTaskCommandParser.java
  src/main/java/seedu/algobase/model/AlgoBase.java
  src/main/java/seedu/algobase/model/Model.java
  src/main/java/seedu/algobase/model/ModelManager.java
  src/main/java/seedu/algobase/model/plan/Plan.java
  src/main/java/seedu/algobase/model/task/Task.java
  src/main/java/seedu/algobase/model/util/SampleDataUtil.java
Labels: status.reviewRequired

#73 Update User Guide and Developer Guide for Tasks
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/algobase/logic/commands/AddCommand.java
  src/main/java/seedu/algobase/logic/commands/AddPlanCommand.java
  src/main/java/seedu/algobase/logic/commands/AddTaskCommand.java
  src/main/java/seedu/algobase/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/algobase/logic/commands/DoneTaskCommand.java
  src/main/java/seedu/algobase/logic/commands/EditCommand.java
  src/main/java/seedu/algobase/logic/commands/EditPlanCommand.java
  src/main/java/seedu/algobase/logic/commands/FindCommand.java
  src/main/java/seedu/algobase/logic/commands/FindPlanCommand.java
  src/main/java/seedu/algobase/logic/commands/HelpCommand.java
  src/main/java/seedu/algobase/logic/commands/SortCommand.java
  src/main/java/seedu/algobase/logic/commands/SwitchCommand.java
  src/main/java/seedu/algobase/logic/commands/UndoneTaskCommand.java
  src/main/java/seedu/algobase/logic/parser/ParserUtil.java
  src/main/java/seedu/algobase/model/problem/Problem.java
Labels: status.reviewRequired

#67 Implementing tag features.
  docs/tutorials/AddRemark.adoc
  src/main/java/seedu/algobase/commons/core/Messages.java
  src/main/java/seedu/algobase/logic/Logic.java
  src/main/java/seedu/algobase/logic/LogicManager.java
  src/main/java/seedu/algobase/logic/commands/AddCommand.java
  src/main/java/seedu/algobase/logic/commands/AddTagCommand.java
  src/main/java/seedu/algobase/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/algobase/logic/commands/EditCommand.java
  src/main/java/seedu/algobase/logic/commands/EditTagCommand.java
  src/main/java/seedu/algobase/logic/commands/ListTagCommand.java
  src/main/java/seedu/algobase/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/algobase/logic/parser/AlgoBaseParser.java
  src/main/java/seedu/algobase/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/algobase/logic/parser/EditTagCommandParser.java
  src/main/java/seedu/algobase/model/AlgoBase.java
  src/main/java/seedu/algobase/model/Model.java
  src/main/java/seedu/algobase/model/ModelManager.java
  src/main/java/seedu/algobase/model/ReadOnlyAlgoBase.java
  src/main/java/seedu/algobase/model/problem/Problem.java
  src/main/java/seedu/algobase/model/tag/Tag.java
  src/main/java/seedu/algobase/model/tag/UniqueTagList.java
  src/main/java/seedu/algobase/model/tag/exceptions/DuplicateTagException.java
  src/main/java/seedu/algobase/model/tag/exceptions/TagNotFoundException.java
  src/main/java/seedu/algobase/storage/JsonSerializableAlgoBase.java
  src/test/java/seedu/algobase/logic/commands/AddCommandTest.java
  src/test/java/seedu/algobase/logic/commands/DefaultModelStub.java
  src/test/java/seedu/algobase/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/algobase/model/tag/TagTest.java
Labels: status.reviewRequired

#85 Ui layout
  src/main/java/seedu/algobase/commons/util/CollectionUtil.java
  src/main/java/seedu/algobase/logic/Logic.java
  src/main/java/seedu/algobase/logic/LogicManager.java
  src/main/java/seedu/algobase/logic/commands/Command.java
  src/main/java/seedu/algobase/logic/commands/OpenTabCommand.java
  src/main/java/seedu/algobase/logic/commands/SwitchCommand.java
  src/main/java/seedu/algobase/logic/commands/SwitchTabCommand.java
  src/main/java/seedu/algobase/logic/parser/AlgoBaseParser.java
  src/main/java/seedu/algobase/logic/parser/CliSyntax.java
  src/main/java/seedu/algobase/logic/parser/OpenTabCommandParser.java
  src/main/java/seedu/algobase/logic/parser/ParserUtil.java
  src/main/java/seedu/algobase/logic/parser/SwitchCommandParser.java
  src/main/java/seedu/algobase/logic/parser/SwitchTabCommandParser.java
  src/main/java/seedu/algobase/model/GuiState.java
  src/main/java/seedu/algobase/model/Model.java
  src/main/java/seedu/algobase/model/ModelManager.java
  src/main/java/seedu/algobase/model/ModelType.java
  src/main/java/seedu/algobase/model/gui/GuiState.java
  src/main/java/seedu/algobase/model/gui/TabData.java
  src/main/java/seedu/algobase/model/gui/TabManager.java
  src/main/java/seedu/algobase/model/gui/TabType.java
  src/main/java/seedu/algobase/ui/MainWindow.java
  src/main/java/seedu/algobase/ui/ProblemDetails.java
  src/main/java/seedu/algobase/ui/details/DetailsTab.java
  src/main/java/seedu/algobase/ui/details/DetailsTabPane.java
  src/main/java/seedu/algobase/ui/display/DisplayTab.java
  src/main/java/seedu/algobase/ui/display/DisplayTabPane.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DetailsTab.fxml
  src/main/resources/view/DetailsTabPane.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ProblemDetails.fxml
  src/test/java/seedu/algobase/logic/commands/DefaultModelStub.java
  src/test/java/seedu/algobase/logic/commands/HelpCommandTest.java
  src/test/java/seedu/algobase/logic/commands/SwitchTabCommandTest.java
  src/test/java/seedu/algobase/model/GuiStateTest.java
  src/test/java/seedu/algobase/model/gui/TabManagerTest.java
Labels: status.reviewRequired

#93 Add design details about Tag in DG
  docs/DeveloperGuide.adoc
  docs/diagrams/AddTagSequenceDiagram.puml
  docs/diagrams/TagActivityDiagram.puml
  docs/images/AddTagSequenceDiagram.png
  docs/images/TagActivityDiagram.png
Labels: documentation

#94 Add implementation details for find command in UG
  docs/DeveloperGuide.adoc
  docs/diagrams/find/FindCommandActivityDiagram.puml
  docs/diagrams/find/FindCommandClassDiagram.puml
  docs/diagrams/find/FindCommandSequenceDiagram.puml
  docs/images/find/FindCommandActivityDiagram.png
  docs/images/find/FindCommandClassDiagram.png
  docs/images/find/FindCommandSequenceDiagram.png
Labels: documentation

#95 Update DG on Design-Model
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: documentation

#80 Update Task Feature
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/gui/SwitchTabsSequenceDiagram0.puml
  docs/diagrams/gui/SwitchTabsSequenceDiagram1.puml
  docs/diagrams/gui/SwitchTabsSequenceDiagram2.puml
  docs/diagrams/gui/style.puml
  docs/diagrams/task/AddTaskCommandActivityDiagram.puml
  docs/diagrams/task/AddTaskSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/task/AddTaskCommandActivityDiagram.png
  docs/images/task/AddTaskSequenceDiagram.png
  src/main/java/seedu/algobase/commons/util/IdUtil.java
  src/main/java/seedu/algobase/logic/commands/AddPlanCommand.java
  src/main/java/seedu/algobase/logic/commands/AddTaskCommand.java
  src/main/java/seedu/algobase/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/algobase/logic/commands/DoneTaskCommand.java
  src/main/java/seedu/algobase/logic/commands/EditCommand.java
  src/main/java/seedu/algobase/logic/commands/EditPlanCommand.java
  src/main/java/seedu/algobase/logic/commands/EditTagCommand.java
  src/main/java/seedu/algobase/logic/commands/UndoneTaskCommand.java
  src/main/java/seedu/algobase/logic/parser/AddPlanCommandParser.java
  src/main/java/seedu/algobase/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/algobase/logic/parser/CliSyntax.java
  src/main/java/seedu/algobase/logic/parser/ParserUtil.java
  src/main/java/seedu/algobase/model/AlgoBase.java
  src/main/java/seedu/algobase/model/plan/Plan.java
  src/main/java/seedu/algobase/model/plan/PlanDescription.java
  src/main/java/seedu/algobase/model/problem/Problem.java
  src/main/java/seedu/algobase/model/tag/Tag.java
  src/main/java/seedu/algobase/model/task/Task.java
  src/main/java/seedu/algobase/model/util/SampleDataUtil.java
  src/main/java/seedu/algobase/storage/JsonAdaptedPlan.java
  src/main/java/seedu/algobase/storage/JsonAdaptedProblem.java
  src/main/java/seedu/algobase/storage/JsonAdaptedTask.java
  src/main/java/seedu/algobase/storage/JsonSerializableAlgoBase.java
  src/main/java/seedu/algobase/ui/PlanCard.java
  src/main/java/seedu/algobase/ui/TaskCard.java
  src/main/resources/view/PlanListCard.fxml
  src/main/resources/view/TaskListCard.fxml
  src/test/java/seedu/algobase/logic/commands/AddTaskCommandTest.java
Labels: status.reviewRequired

#91 Plan storage
  docs/DeveloperGuide.adoc
  docs/diagrams/LogicClassDiagram.puml
  docs/images/LogicClassDiagram.png
  src/main/java/seedu/algobase/model/AlgoBase.java
  src/main/java/seedu/algobase/storage/JsonAlgoBaseStorage.java
Labels: status.reviewRequired

#99 Simplify UML diagrams in DG
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/design/model/BetterModelClassDiagram.puml
  docs/diagrams/design/model/GuiPackageDiagram.puml
  docs/diagrams/design/model/ModelClassDiagram.puml
  docs/diagrams/design/model/PlanPackageDiagram.puml
  docs/diagrams/design/model/ProblemPackageDiagram.puml
  docs/diagrams/design/model/TagPackageDiagram.puml
  docs/diagrams/design/model/TaskPackageDiagram.puml
  docs/diagrams/find/FindCommandClassDiagram.puml
  docs/diagrams/find/FindCommandSequenceDiagram.puml
  docs/diagrams/find/PredicateClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/design/model/BetterModelClassDiagram.png
  docs/images/design/model/GuiPackageDiagram.png
  docs/images/design/model/ModelClassDiagram.png
  docs/images/design/model/PlanPackageDiagram.png
  docs/images/design/model/ProblemPackageDiagram.png
  docs/images/design/model/TagPackageDiagram.png
  docs/images/design/model/TaskPackageDiagram.png
  docs/images/find/FindCommandClassDiagram.png
  docs/images/find/FindCommandSequenceDiagram.png
  docs/images/find/PredicateClassDiagram.png
Labels: documentation

#90 Implement saving feature for find rules
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/design/model/ModelClassDiagram.puml
  docs/diagrams/design/model/ProblemSearchRulePackageDiagram.puml
  docs/images/design/model/ModelClassDiagram.png
  docs/images/design/model/ProblemSearchRulePackageDiagram.png
  src/main/java/seedu/algobase/commons/core/Messages.java
  src/main/java/seedu/algobase/logic/Logic.java
  src/main/java/seedu/algobase/logic/LogicManager.java
  src/main/java/seedu/algobase/logic/commands/AddFindRuleCommand.java
  src/main/java/seedu/algobase/logic/commands/ApplyCommand.java
  src/main/java/seedu/algobase/logic/commands/DeleteCommand.java
  src/main/java/seedu/algobase/logic/commands/DeleteFindRuleCommand.java
  src/main/java/seedu/algobase/logic/commands/FindCommand.java
  src/main/java/seedu/algobase/logic/parser/AddFindRuleCommandParser.java
  src/main/java/seedu/algobase/logic/parser/AlgoBaseParser.java
  src/main/java/seedu/algobase/logic/parser/ApplyCommandParser.java
  src/main/java/seedu/algobase/logic/parser/DeleteFindRuleParser.java
  src/main/java/seedu/algobase/logic/parser/FindCommandParser.java
  src/main/java/seedu/algobase/model/AlgoBase.java
  src/main/java/seedu/algobase/model/Model.java
  src/main/java/seedu/algobase/model/ModelManager.java
  src/main/java/seedu/algobase/model/ModelType.java
  src/main/java/seedu/algobase/model/ReadOnlyAlgoBase.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/AuthorMatchesKeywordPredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/DescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/DifficultyIsInRangePredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/FindProblemDescriptor.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/Keyword.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/Name.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/NameContainsKeywordsPredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/ProblemSearchRule.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/SourceMatchesKeywordPredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/TagIncludesKeywordsPredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/UniqueFindRuleList.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/exceptions/DuplicateProblemSearchRuleException.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/exceptions/ProblemSearchRuleNotFoundException.java
  src/main/java/seedu/algobase/storage/JsonAdaptedAuthorMatchesKeywordPredicate.java
  src/main/java/seedu/algobase/storage/JsonAdaptedDescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/algobase/storage/JsonAdaptedDifficultyIsInRangePredicate.java
  src/main/java/seedu/algobase/storage/JsonAdaptedKeyword.java
  src/main/java/seedu/algobase/storage/JsonAdaptedNameContainsKeywordsPredicate.java
  src/main/java/seedu/algobase/storage/JsonAdaptedProblemSearchRule.java
  src/main/java/seedu/algobase/storage/JsonAdaptedSourceMatchesKeywordPredicate.java
  src/main/java/seedu/algobase/storage/JsonAdaptedTagIncludesKeywordsPredicate.java
  src/main/java/seedu/algobase/storage/JsonSerializableAlgoBase.java
  src/main/java/seedu/algobase/ui/FindRuleCard.java
  src/main/java/seedu/algobase/ui/FindRuleListPanel.java
  src/main/java/seedu/algobase/ui/MainWindow.java
  src/main/resources/view/FindRuleListCard.fxml
  src/main/resources/view/FindRuleListPanel.fxml
  src/test/java/seedu/algobase/logic/commands/CommandTestUtil.java
  src/test/java/seedu/algobase/logic/commands/DefaultModelStub.java
  src/test/java/seedu/algobase/model/problem/AuthorMatchesKeywordPredicateTest.java
  src/test/java/seedu/algobase/model/problem/DescriptionContainsKeywordsPredicateTest.java
  src/test/java/seedu/algobase/model/problem/DifficultyIsInRangePredicateTest.java
  src/test/java/seedu/algobase/model/problem/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/algobase/model/problem/SourceMatchesKeywordPredicateTest.java
  src/test/java/seedu/algobase/model/problem/TagIncludesKeywordsPredicateTest.java
Labels: status.reviewRequired

#105 Implement rewind command feature
  docs/UserGuide.adoc
  src/main/java/seedu/algobase/commons/core/Messages.java
  src/main/java/seedu/algobase/logic/LogicManager.java
  src/main/java/seedu/algobase/logic/commands/CommandResult.java
  src/main/java/seedu/algobase/logic/commands/ExitCommand.java
  src/main/java/seedu/algobase/logic/commands/HelpCommand.java
  src/main/java/seedu/algobase/logic/commands/RewindCommand.java
  src/main/java/seedu/algobase/logic/parser/AlgoBaseParser.java
  src/main/java/seedu/algobase/logic/parser/RewindCommandParser.java
  src/main/java/seedu/algobase/model/AlgoBase.java
  src/main/java/seedu/algobase/model/Model.java
  src/main/java/seedu/algobase/model/ModelManager.java
  src/main/java/seedu/algobase/model/ReadOnlyAlgoBase.java
  src/main/java/seedu/algobase/model/commandhistory/CommandHistory.java
  src/main/java/seedu/algobase/model/commandhistory/CommandHistoryList.java
  src/main/java/seedu/algobase/ui/CommandBox.java
  src/main/java/seedu/algobase/ui/MainWindow.java
  src/main/resources/view/FindRuleListCard.fxml
  src/test/java/seedu/algobase/logic/commands/DefaultModelStub.java
  src/test/java/seedu/algobase/logic/commands/HelpCommandTest.java
Labels: status.reviewRequired

#108 add Tags UI and change UG for tag
  docs/UserGuide.adoc
  src/main/java/seedu/algobase/logic/Logic.java
  src/main/java/seedu/algobase/logic/LogicManager.java
  src/main/java/seedu/algobase/logic/commands/ClearCommand.java
  src/main/java/seedu/algobase/logic/commands/EditTagCommand.java
  src/main/java/seedu/algobase/logic/commands/ExitCommand.java
  src/main/java/seedu/algobase/logic/commands/ListCommand.java
  src/main/java/seedu/algobase/logic/commands/ListPlanCommand.java
  src/main/java/seedu/algobase/logic/commands/ListTagCommand.java
  src/main/java/seedu/algobase/ui/HelpWindow.java
  src/main/java/seedu/algobase/ui/MainWindow.java
  src/main/java/seedu/algobase/ui/TagCard.java
  src/main/java/seedu/algobase/ui/TagListPanel.java
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/TagListCard.fxml
  src/main/resources/view/TagListPanel.fxml
Labels: priority.High, status.Ongoing

#107 Add tests for saving find rules
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/find/FindCommandSequenceDiagram.puml
  docs/diagrams/savefindrule/AddFindRuleActivityDiagram.puml
  docs/diagrams/savefindrule/AddFindRuleClassDiagram.puml
  docs/diagrams/savefindrule/AddFindRuleSequenceDiagram.puml
  docs/diagrams/savefindrule/HighLevelAddFindRuleSequenceDiagram.puml
  docs/images/find/FindCommandSequenceDiagram.png
  docs/images/savefindrule/AddFindRuleActivityDiagram.png
  docs/images/savefindrule/AddFindRuleClassDiagram.png
  docs/images/savefindrule/AddFindRuleSequenceDiagram.png
  docs/images/savefindrule/HighLevelAddFindRuleSequenceDiagram.png
  src/main/java/seedu/algobase/commons/core/Messages.java
  src/main/java/seedu/algobase/commons/util/AppUtil.java
  src/main/java/seedu/algobase/logic/commands/FindCommand.java
  src/main/java/seedu/algobase/logic/parser/AddFindRuleCommandParser.java
  src/main/java/seedu/algobase/logic/parser/FindCommandParser.java
  src/main/java/seedu/algobase/logic/parser/ParserUtil.java
  src/main/java/seedu/algobase/logic/parser/SortCommandParser.java
  src/main/java/seedu/algobase/model/problem/Difficulty.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/AuthorMatchesKeywordPredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/DescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/DifficultyIsInRangePredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/FindProblemDescriptor.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/NameContainsKeywordsPredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/ProblemSearchRule.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/SourceMatchesKeywordPredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/TagIncludesKeywordsPredicate.java
  src/main/java/seedu/algobase/storage/JsonAdaptedDifficultyIsInRangePredicate.java
  src/main/java/seedu/algobase/storage/JsonAdaptedProblemSearchRule.java
  src/main/java/seedu/algobase/ui/FindRuleCard.java
  src/main/resources/view/FindRuleListCard.fxml
  src/main/resources/view/FindRuleListPanel.fxml
  src/test/java/seedu/algobase/logic/commands/AddFindRuleCommandTest.java
  src/test/java/seedu/algobase/logic/commands/ApplyCommandTest.java
  src/test/java/seedu/algobase/logic/commands/DeleteFindRuleCommandTest.java
  src/test/java/seedu/algobase/logic/commands/FindCommandTest.java
  src/test/java/seedu/algobase/logic/commands/SortCommandTest.java
  src/test/java/seedu/algobase/model/searchrule/problemsearchrule/AuthorMatchesKeywordPredicateTest.java
  src/test/java/seedu/algobase/model/searchrule/problemsearchrule/DescriptionContainsKeywordsPredicateTest.java
  src/test/java/seedu/algobase/model/searchrule/problemsearchrule/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/algobase/model/searchrule/problemsearchrule/ProblemSearchRuleTest.java
  src/test/java/seedu/algobase/model/searchrule/problemsearchrule/SourceMatchesKeywordPredicateTest.java
  src/test/java/seedu/algobase/model/searchrule/problemsearchrule/TagIncludesKeywordsPredicateTest.java
  src/test/java/seedu/algobase/storage/JsonAdaptedAuthorMatchesKeywordPredicateTest.java
  src/test/java/seedu/algobase/storage/JsonAdaptedDescriptionContainsKeywordsPredicateTest.java
  src/test/java/seedu/algobase/storage/JsonAdaptedKeywordTest.java
  src/test/java/seedu/algobase/storage/JsonAdaptedNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/algobase/storage/JsonAdaptedProblemSearchRuleTest.java
  src/test/java/seedu/algobase/storage/JsonAdaptedSourceMatchesKeywordPredicateTest.java
  src/test/java/seedu/algobase/storage/JsonAdaptedTagIncludesKeywordsPredicateTest.java
  src/test/java/seedu/algobase/testutil/FindProblemDescriptorBuilder.java
  src/test/java/seedu/algobase/testutil/TypicalIndexes.java
  src/test/java/seedu/algobase/testutil/TypicalProblemSearchRules.java
  src/test/java/seedu/algobase/testutil/TypicalProblems.java
Labels: status.reviewRequired

#106 Close tab
  docs/DeveloperGuide.adoc
  docs/diagrams/gui/SwitchTabsSequenceDiagram3.puml
  docs/images/gui/SwitchTabsSequenceDiagram3.png
  src/main/java/seedu/algobase/MainApp.java
  src/main/java/seedu/algobase/commons/util/IdUtil.java
  src/main/java/seedu/algobase/logic/commands/CloseTabCommand.java
  src/main/java/seedu/algobase/logic/commands/EditCommand.java
  src/main/java/seedu/algobase/logic/commands/EditPlanCommand.java
  src/main/java/seedu/algobase/logic/commands/EditTagCommand.java
  src/main/java/seedu/algobase/logic/commands/ListCommand.java
  src/main/java/seedu/algobase/logic/commands/ListPlanCommand.java
  src/main/java/seedu/algobase/logic/commands/ListTagCommand.java
  src/main/java/seedu/algobase/logic/commands/OpenTabCommand.java
  src/main/java/seedu/algobase/logic/parser/AlgoBaseParser.java
  src/main/java/seedu/algobase/logic/parser/CloseTabCommandParser.java
  src/main/java/seedu/algobase/model/AlgoBase.java
  src/main/java/seedu/algobase/model/Id.java
  src/main/java/seedu/algobase/model/ModelManager.java
  src/main/java/seedu/algobase/model/ModelType.java
  src/main/java/seedu/algobase/model/ReadOnlyAlgoBase.java
  src/main/java/seedu/algobase/model/gui/GuiState.java
  src/main/java/seedu/algobase/model/gui/ReadOnlyGuiState.java
  src/main/java/seedu/algobase/model/gui/ReadOnlyTabManager.java
  src/main/java/seedu/algobase/model/gui/TabData.java
  src/main/java/seedu/algobase/model/gui/TabManager.java
  src/main/java/seedu/algobase/model/gui/UniqueTabDataList.java
  src/main/java/seedu/algobase/model/gui/WriteOnlyTabManager.java
  src/main/java/seedu/algobase/model/gui/exceptions/DuplicateTabDataException.java
  src/main/java/seedu/algobase/model/gui/exceptions/TabDataNotFoundException.java
  src/main/java/seedu/algobase/model/plan/Plan.java
  src/main/java/seedu/algobase/model/problem/Problem.java
  src/main/java/seedu/algobase/model/tag/Tag.java
  src/main/java/seedu/algobase/model/task/Task.java
  src/main/java/seedu/algobase/model/util/SampleDataUtil.java
  src/main/java/seedu/algobase/storage/JsonAdaptedGuiState.java
  src/main/java/seedu/algobase/storage/JsonAdaptedPlan.java
  src/main/java/seedu/algobase/storage/JsonAdaptedProblem.java
  src/main/java/seedu/algobase/storage/JsonAdaptedTab.java
  src/main/java/seedu/algobase/storage/JsonAdaptedTabManager.java
  src/main/java/seedu/algobase/storage/JsonAdaptedTask.java
  src/main/java/seedu/algobase/storage/JsonSerializableAlgoBase.java
  src/main/java/seedu/algobase/ui/MainWindow.java
  src/main/java/seedu/algobase/ui/PlanCard.java
  src/main/java/seedu/algobase/ui/PlanListPanel.java
  src/main/java/seedu/algobase/ui/ProblemCard.java
  src/main/java/seedu/algobase/ui/ProblemListPanel.java
  src/main/java/seedu/algobase/ui/details/DetailsTab.java
  src/main/java/seedu/algobase/ui/details/DetailsTabPane.java
  src/main/java/seedu/algobase/ui/details/PlanDetails.java
  src/main/java/seedu/algobase/ui/details/ProblemDetails.java
  src/main/java/seedu/algobase/ui/display/DisplayTabPane.java
  src/main/resources/view/PlanDetails.fxml
  src/main/resources/view/ProblemDetails.fxml
  src/test/java/seedu/algobase/logic/commands/CloseTabCommandTest.java
  src/test/java/seedu/algobase/logic/commands/OpenTabCommandTest.java
  src/test/java/seedu/algobase/logic/commands/SwitchTabCommandTest.java
  src/test/java/seedu/algobase/model/gui/TabManagerTest.java
Labels: status.reviewRequired

#117 Find plans
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/design/model/PlanPackageDiagram.puml
  docs/diagrams/design/model/PlanSearchRulePackageDiagram.puml
  docs/diagrams/design/model/TaskPackageDiagram.puml
  docs/images/design/model/PlanPackageDiagram.png
  docs/images/design/model/PlanSearchRulePackageDiagram.png
  src/main/java/seedu/algobase/logic/commands/AddPlanCommand.java
  src/main/java/seedu/algobase/logic/commands/EditPlanCommand.java
  src/main/java/seedu/algobase/logic/commands/FindPlanCommand.java
  src/main/java/seedu/algobase/logic/parser/FindPlanCommandParser.java
  src/main/java/seedu/algobase/logic/parser/ParserUtil.java
  src/main/java/seedu/algobase/model/searchrule/plansearchrule/FindPlanDescriptor.java
  src/main/java/seedu/algobase/model/searchrule/plansearchrule/Keyword.java
  src/main/java/seedu/algobase/model/searchrule/plansearchrule/PlanDescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/algobase/model/searchrule/plansearchrule/PlanNameContainsKeywordsPredicate.java
  src/main/java/seedu/algobase/model/searchrule/plansearchrule/TimeRange.java
  src/main/java/seedu/algobase/model/searchrule/plansearchrule/TimeRangePredicate.java
  src/main/java/seedu/algobase/storage/JsonAdaptedPlan.java
  src/main/java/seedu/algobase/storage/JsonAdaptedTask.java
Labels: status.reviewRequired

#125 Minor update to README
  README.adoc
  docs/DeveloperGuide.adoc
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskManagementPane.fxml
Labels: status.reviewRequired

#123 Update Quick Start
  docs/UserGuide.adoc
  docs/images/UiStartPlan.png
  src/main/java/seedu/algobase/logic/parser/FindPlanCommandParser.java
  src/main/java/seedu/algobase/logic/parser/ParserUtil.java
Labels: documentation

#145 Fix description of tag in UG
  docs/UserGuide.adoc
  src/main/java/seedu/algobase/logic/commands/problem/EditCommand.java
  src/main/java/seedu/algobase/model/AlgoBase.java
  src/main/java/seedu/algobase/model/problem/Name.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/Name.java
  src/main/java/seedu/algobase/model/util/SampleDataUtil.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/TagListCard.fxml
Labels: status.reviewRequired

#150 Remove corresponding tasks from plans when a problem is deleted
  src/main/java/seedu/algobase/logic/commands/problem/DeleteCommand.java
  src/main/java/seedu/algobase/logic/parser/CliSyntax.java
  src/main/java/seedu/algobase/logic/parser/problem/DeleteCommandParser.java
  src/main/java/seedu/algobase/model/AlgoBase.java
  src/main/java/seedu/algobase/model/Model.java
  src/main/java/seedu/algobase/model/ModelManager.java
  src/main/java/seedu/algobase/model/ReadOnlyAlgoBase.java
  src/main/java/seedu/algobase/model/plan/Plan.java
  src/main/java/seedu/algobase/model/plan/PlanList.java
  src/main/java/seedu/algobase/storage/JsonAdaptedTask.java
  src/test/java/seedu/algobase/logic/commands/DefaultModelStub.java
Labels: status.reviewRequired

#147 Update tabs
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/gui/SwitchTabsSequenceDiagram0.puml
  docs/images/gui/OpenTabCommand.png
  docs/images/gui/SwitchTabCommand.png
  docs/images/gui/SwitchTabsSequenceDiagram0.png
  docs/images/gui/TabsOverview.png
  src/main/java/seedu/algobase/logic/commands/CloseTabCommand.java
  src/main/java/seedu/algobase/logic/commands/OpenTabCommand.java
  src/main/java/seedu/algobase/logic/commands/SwitchTabCommand.java
  src/main/java/seedu/algobase/logic/parser/AlgoBaseParser.java
  src/main/java/seedu/algobase/logic/parser/CliSyntax.java
  src/main/java/seedu/algobase/logic/parser/CloseTabCommandParser.java
  src/main/java/seedu/algobase/logic/parser/OpenTabCommandParser.java
  src/main/java/seedu/algobase/logic/parser/ParserUtil.java
  src/main/java/seedu/algobase/logic/parser/SwitchTabCommandParser.java
  src/main/java/seedu/algobase/model/gui/TabManager.java
  src/main/java/seedu/algobase/model/gui/WriteOnlyTabManager.java
  src/main/java/seedu/algobase/ui/PlanCard.java
  src/main/java/seedu/algobase/ui/ProblemCard.java
  src/main/java/seedu/algobase/ui/details/DetailsTabPane.java
  src/main/java/seedu/algobase/ui/details/ProblemDetails.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PlanDetails.fxml
  src/main/resources/view/PlanListCard.fxml
  src/main/resources/view/ProblemDetails.fxml
  src/main/resources/view/ProblemListCard.fxml
  src/main/resources/view/TaskListCard.fxml
Labels: documentation, status.reviewRequired

#157 Minor fixes
  docs/UserGuide.adoc
  src/main/java/seedu/algobase/logic/commands/Command.java
  src/main/java/seedu/algobase/logic/commands/findrule/AddFindRuleCommand.java
  src/main/java/seedu/algobase/logic/commands/findrule/ApplyCommand.java
  src/main/java/seedu/algobase/logic/commands/findrule/DeleteFindRuleCommand.java
  src/main/java/seedu/algobase/logic/parser/AlgoBaseParser.java
  src/main/java/seedu/algobase/logic/parser/findrule/AddFindRuleCommandParser.java
  src/main/java/seedu/algobase/logic/parser/findrule/ApplyCommandParser.java
  src/main/java/seedu/algobase/logic/parser/findrule/DeleteFindRuleParser.java
  src/main/java/seedu/algobase/model/plan/PlanName.java
  src/main/java/seedu/algobase/model/problem/Name.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/Name.java
  src/main/java/seedu/algobase/model/util/SampleDataUtil.java
  src/main/java/seedu/algobase/ui/FindRuleCard.java
  src/main/resources/view/FindRuleListCard.fxml
  src/test/java/seedu/algobase/logic/commands/AddFindRuleCommandTest.java
  src/test/java/seedu/algobase/logic/commands/ApplyCommandTest.java
  src/test/java/seedu/algobase/logic/commands/DeleteFindRuleCommandTest.java
Labels: status.reviewRequired

#162 Add more sample data
  src/main/java/seedu/algobase/model/util/SampleDataUtil.java
Labels: status.reviewRequired

#164 Update UI and Fix Minor Bugs
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/UiStartPlan.png
  src/main/java/seedu/algobase/logic/commands/AddPlanCommand.java
  src/main/java/seedu/algobase/logic/commands/problem/AddCommand.java
  src/main/java/seedu/algobase/logic/commands/problem/DeleteCommand.java
  src/main/java/seedu/algobase/logic/commands/task/AddTaskCommand.java
  src/main/java/seedu/algobase/logic/commands/task/CopyTaskCommand.java
  src/main/java/seedu/algobase/logic/commands/task/DeleteTaskCommand.java
  src/main/java/seedu/algobase/logic/commands/task/DoneTaskCommand.java
  src/main/java/seedu/algobase/logic/commands/task/EditTaskCommand.java
  src/main/java/seedu/algobase/logic/commands/task/MoveTaskCommand.java
  src/main/java/seedu/algobase/logic/commands/task/SetPlanCommand.java
  src/main/java/seedu/algobase/logic/commands/task/UndoneTaskCommand.java
  src/main/java/seedu/algobase/logic/parser/AddPlanCommandParser.java
  src/main/java/seedu/algobase/model/plan/PlanList.java
  src/main/java/seedu/algobase/ui/MainWindow.java
  src/main/java/seedu/algobase/ui/TaskCard.java
  src/main/java/seedu/algobase/ui/TaskManagementPane.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TagListCard.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskManagementPane.fxml
Labels: status.reviewRequired
