Repository AY1920S1-CS2103T-W11-1/main, pull requests merged in 2019-11, with the labels that each got.

#165 Fix tag add delete and edit bugs
  src/main/java/seedu/algobase/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/algobase/model/ModelManager.java
  src/main/java/seedu/algobase/model/tag/UniqueTagList.java
  src/main/resources/view/MainWindow.fxml
Labels: status.reviewRequired

#200 Fix PE tabs issues
  src/main/java/seedu/algobase/logic/Logic.java
  src/main/java/seedu/algobase/logic/LogicManager.java
  src/main/java/seedu/algobase/logic/commands/Command.java
  src/main/java/seedu/algobase/logic/commands/ListPlanCommand.java
  src/main/java/seedu/algobase/logic/commands/ListTagCommand.java
  src/main/java/seedu/algobase/logic/commands/gui/CloseTabCommand.java
  src/main/java/seedu/algobase/logic/commands/gui/OpenTabCommand.java
  src/main/java/seedu/algobase/logic/commands/gui/SwitchTabCommand.java
  src/main/java/seedu/algobase/logic/commands/problem/ListCommand.java
  src/main/java/seedu/algobase/logic/parser/AlgoBaseParser.java
  src/main/java/seedu/algobase/logic/parser/CloseTabCommandParser.java
  src/main/java/seedu/algobase/logic/parser/OpenTabCommandParser.java
  src/main/java/seedu/algobase/logic/parser/SwitchTabCommandParser.java
  src/main/java/seedu/algobase/model/ModelType.java
  src/main/java/seedu/algobase/model/gui/TabCommandType.java
  src/main/java/seedu/algobase/model/gui/TabManager.java
  src/main/java/seedu/algobase/model/gui/UniqueTabDataList.java
  src/main/java/seedu/algobase/model/gui/WriteOnlyTabManager.java
  src/main/java/seedu/algobase/model/util/SampleDataUtil.java
  src/main/java/seedu/algobase/storage/JsonAdaptedTabManager.java
  src/main/java/seedu/algobase/storage/SaveStorageRunnable.java
  src/main/java/seedu/algobase/storage/exceptions/StorageException.java
  src/main/java/seedu/algobase/ui/MainWindow.java
  src/main/java/seedu/algobase/ui/PlanCard.java
  src/main/java/seedu/algobase/ui/PlanListPanel.java
  src/main/java/seedu/algobase/ui/ProblemCard.java
  src/main/java/seedu/algobase/ui/ProblemListPanel.java
  src/main/java/seedu/algobase/ui/details/DetailsTab.java
  src/main/java/seedu/algobase/ui/details/DetailsTabPane.java
  src/main/java/seedu/algobase/ui/details/ProblemDetails.java
  src/main/java/seedu/algobase/ui/display/DisplayTabPane.java
  src/test/java/seedu/algobase/logic/LogicManagerTest.java
  src/test/java/seedu/algobase/logic/commands/CloseTabCommandTest.java
  src/test/java/seedu/algobase/logic/commands/OpenTabCommandTest.java
  src/test/java/seedu/algobase/logic/commands/SwitchTabCommandTest.java
  src/test/java/seedu/algobase/model/gui/TabManagerTest.java
Labels: status.reviewRequired

#201 Fix add and edit empty tag bug.
  src/main/java/seedu/algobase/logic/commands/EditTagCommand.java
  src/main/java/seedu/algobase/logic/parser/ParserUtil.java
  src/main/java/seedu/algobase/model/tag/Tag.java
Labels: status.reviewRequired

#197 Fix typo in userguide and change error message
  docs/UserGuide.adoc
  src/main/java/seedu/algobase/model/problem/WebLink.java
Labels: documentation, type.Bug

#204 Fix PED issues
  docs/UserGuide.adoc
  docs/images/apply_tip_find_rule_tab.png
  src/main/java/seedu/algobase/logic/commands/problem/SortCommand.java
Labels: status.reviewRequired

#211 Bug fixes on `find` and `dfr`
  docs/UserGuide.adoc
  src/main/java/seedu/algobase/logic/commands/findrule/DeleteFindRuleCommand.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/AuthorMatchesKeywordPredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/SourceMatchesKeywordPredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/TagIncludesKeywordsPredicate.java
  src/test/java/seedu/algobase/integration/FindCommandIntegrationTest.java
  src/test/java/seedu/algobase/logic/commands/DeleteFindRuleCommandTest.java
Labels: status.reviewRequired

#207 Add some integration tests
  src/test/java/seedu/algobase/integration/AddPlanCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/AddProblemCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/AddTagCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/AddTaskCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/DeleteFindRuleCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/DeletePlanCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/DeleteProblemCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/DeleteTagCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/DoneTaskCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/EditPlanCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/EditProblemCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/EditTagCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/EditTaskCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/FindCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/HelpCommandIntegrationTest
  src/test/java/seedu/algobase/integration/ListCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/SortProblemCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/UndoneTaskCommandIntegrationTest.java
Labels: status.reviewRequired

#216 Fix `deletetag` and `edittag` bugs
  src/main/java/seedu/algobase/logic/commands/Command.java
  src/main/java/seedu/algobase/logic/commands/tag/AddTagCommand.java
  src/main/java/seedu/algobase/logic/commands/tag/DeleteTagCommand.java
  src/main/java/seedu/algobase/logic/commands/tag/EditTagCommand.java
  src/main/java/seedu/algobase/logic/commands/tag/ListTagCommand.java
  src/main/java/seedu/algobase/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/algobase/logic/parser/AlgoBaseParser.java
  src/main/java/seedu/algobase/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/algobase/logic/parser/EditTagCommandParser.java
  src/main/resources/view/DetailsTab.fxml
  src/main/resources/view/DetailsTabPane.fxml
  src/main/resources/view/DisplayTab.fxml
  src/main/resources/view/DisplayTabPane.fxml
  src/main/resources/view/PlanDetails.fxml
  src/main/resources/view/PlanListCard.fxml
  src/main/resources/view/ProblemDetails.fxml
  src/main/resources/view/TaskManagementPane.fxml
  src/test/java/seedu/algobase/logic/commands/DeleteTagCommandTest.java
Labels: status.reviewRequired

#119 Update project portfolio page
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/design/model/PlanPackageDiagram.puml
  docs/images/design/model/PlanPackageDiagram.png
  docs/team/le0tan.adoc
  docs/team/le0tan.pdf
Labels: documentation

#218 Fix description in UG
  docs/UserGuide.adoc
  docs/team/luwenq.adoc
Labels: documentation

#220 Update PPP
  README.adoc
  docs/UserGuide.adoc
  docs/team/jiayushe.adoc
Labels: documentation, status.reviewRequired

#224 Tests, Assertions, Logging, Cleanup and Documentation for UiLogic
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/gui/AlgoBaseLayout.png
  docs/images/gui/DeleteProblemUiAction1.png
  docs/team/tiuweehan.adoc
  src/main/java/seedu/algobase/logic/commands/gui/OpenTabCommand.java
  src/main/java/seedu/algobase/ui/PlanCard.java
  src/main/java/seedu/algobase/ui/ProblemCard.java
  src/main/java/seedu/algobase/ui/action/UiAction.java
  src/main/java/seedu/algobase/ui/action/UiActionDetails.java
  src/main/java/seedu/algobase/ui/action/UiActionResult.java
  src/main/java/seedu/algobase/ui/action/UiLogicManager.java
  src/main/java/seedu/algobase/ui/action/actions/OpenDetailsTabUiAction.java
  src/main/java/seedu/algobase/ui/action/actions/SwitchDetailsTabUiAction.java
  src/main/java/seedu/algobase/ui/action/actions/SwitchDisplayTabUiAction.java
  src/main/java/seedu/algobase/ui/action/parser/AlgoBaseUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/CloseDetailsTabUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/DeletePlanUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/DeleteProblemUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/EditPlanUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/EditProblemUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/OpenDetailsTabUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/SetPlanUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/SwitchDetailsTabUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/SwitchDisplayTabUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/UiParserUtil.java
  src/main/java/seedu/algobase/ui/details/DetailsTab.java
  src/main/java/seedu/algobase/ui/details/DetailsTabPane.java
  src/main/java/seedu/algobase/ui/details/PlanDetails.java
  src/main/java/seedu/algobase/ui/details/ProblemDetails.java
  src/main/java/seedu/algobase/ui/details/WarningDialog.java
  src/main/java/seedu/algobase/ui/display/DisplayTabPane.java
  src/test/java/seedu/algobase/ui/action/actions/CloseDetailsTabUiActionTest.java
  src/test/java/seedu/algobase/ui/action/actions/DeletePlanUiActionTest.java
  src/test/java/seedu/algobase/ui/action/actions/DeleteProblemUiActionTest.java
  src/test/java/seedu/algobase/ui/action/actions/EditPlanUiActionTest.java
  src/test/java/seedu/algobase/ui/action/actions/EditProblemUiActionTest.java
  src/test/java/seedu/algobase/ui/action/actions/OpenDetailsTabUiActionTest.java
  src/test/java/seedu/algobase/ui/action/actions/SetPlanUiActionTest.java
  src/test/java/seedu/algobase/ui/action/actions/SwitchDetailsTabUiActionTest.java
  src/test/java/seedu/algobase/ui/action/actions/SwitchDisplayTabUiActionTest.java
  src/test/java/seedu/algobase/ui/action/parser/CloseDetailsTabUiActionParserTest.java
  src/test/java/seedu/algobase/ui/action/parser/DeletePlanUiActionParserTest.java
  src/test/java/seedu/algobase/ui/action/parser/DeleteProblemUiActionParserTest.java
  src/test/java/seedu/algobase/ui/action/parser/EditPlanUiActionParserTest.java
  src/test/java/seedu/algobase/ui/action/parser/EditProblemUiActionParserTest.java
  src/test/java/seedu/algobase/ui/action/parser/OpenDetailsTabUiActionParserTest.java
  src/test/java/seedu/algobase/ui/action/parser/SetPlanUiActionParserTest.java
  src/test/java/seedu/algobase/ui/action/parser/SwitchDetailsTabUiActionParserTest.java
  src/test/java/seedu/algobase/ui/action/parser/SwitchDisplayTabUiActionParserTest.java
Labels: priority.Medium, status.reviewRequired

#232 Minor fixes on documentation and message usage
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/le0tan.adoc
  docs/team/le0tan.pdf
  src/main/java/seedu/algobase/logic/commands/findrule/ApplyCommand.java
  src/main/java/seedu/algobase/logic/commands/findrule/DeleteFindRuleCommand.java
  src/main/java/seedu/algobase/logic/commands/problem/FindCommand.java
Labels: documentation

#233 Improve UI for blank fields
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/gui/OpenTabUiActionActivityDiagram.puml
  docs/images/gui/AlgoBaseLayout.png
  docs/images/gui/DeleteProblemUiAction0.png
  docs/images/gui/DeleteProblemUiAction0Annotated.png
  docs/images/gui/DeleteProblemUiAction1.png
  docs/images/gui/DeleteProblemUiAction1Annotated.png
  docs/images/gui/DeleteProblemUiAction2.png
  docs/images/gui/DeleteProblemUiAction2Annotated.png
  docs/images/gui/EditPlanUiAction0.png
  docs/images/gui/EditPlanUiAction0Annotated.png
  docs/images/gui/EditPlanUiAction1.png
  docs/images/gui/EditPlanUiAction1Annotated.png
  docs/images/gui/EditPlanUiAction2.png
  docs/images/gui/EditPlanUiAction2Annotated.png
  docs/images/gui/OpenDetailsTabUiActionActivityDiagram.png
  docs/images/gui/OpenTabUiActionActivityDiagram.png
  docs/images/gui/TabsOverview1.png
  docs/team/tiuweehan.adoc
  src/main/java/seedu/algobase/ui/PlanCard.java
  src/main/java/seedu/algobase/ui/ProblemCard.java
  src/main/java/seedu/algobase/ui/action/parser/EditProblemUiActionParser.java
  src/main/java/seedu/algobase/ui/details/ProblemDetails.java
Labels: status.reviewRequired

#235 Bug fixes and documentation improvements
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/find_rule_1.png
  docs/images/findprob_1.png
  docs/team/le0tan.adoc
  src/main/java/seedu/algobase/commons/util/AppUtil.java
  src/main/java/seedu/algobase/logic/commands/HelpCommand.java
  src/main/java/seedu/algobase/logic/commands/findrule/ApplyCommand.java
  src/main/java/seedu/algobase/logic/commands/findrule/DeleteFindRuleCommand.java
  src/main/java/seedu/algobase/logic/commands/problem/SortCommand.java
  src/main/java/seedu/algobase/logic/parser/HelpCommandParser.java
  src/main/java/seedu/algobase/logic/parser/ParserUtil.java
  src/main/java/seedu/algobase/logic/parser/findrule/AddFindRuleCommandParser.java
  src/main/java/seedu/algobase/logic/parser/findrule/ApplyCommandParser.java
  src/main/java/seedu/algobase/logic/parser/findrule/DeleteFindRuleParser.java
  src/main/java/seedu/algobase/logic/parser/problem/AddCommandParser.java
  src/main/java/seedu/algobase/logic/parser/problem/FindCommandParser.java
  src/main/java/seedu/algobase/logic/parser/problem/SortCommandParser.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/AuthorMatchesKeywordPredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/DescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/DifficultyIsInRangePredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/FindProblemDescriptor.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/Keyword.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/NameContainsKeywordsPredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/SourceMatchesKeywordPredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/TagIncludesKeywordsPredicate.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/UniqueFindRuleList.java
  src/main/java/seedu/algobase/storage/JsonAdaptedAuthorMatchesKeywordPredicate.java
  src/main/java/seedu/algobase/storage/JsonAdaptedDescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/algobase/storage/JsonAdaptedDifficultyIsInRangePredicate.java
  src/main/java/seedu/algobase/storage/JsonAdaptedKeyword.java
  src/main/java/seedu/algobase/storage/JsonAdaptedNameContainsKeywordsPredicate.java
  src/main/java/seedu/algobase/storage/JsonAdaptedSourceMatchesKeywordPredicate.java
  src/main/java/seedu/algobase/storage/JsonAdaptedTagIncludesKeywordsPredicate.java
  src/main/java/seedu/algobase/storage/util/StorageUtil.java
Labels: documentation, status.reviewRequired

#236 Update Documentation and Fix Bugs
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/tiuweehan.adoc
  src/main/java/seedu/algobase/logic/parser/AlgoBaseParser.java
  src/main/java/seedu/algobase/ui/action/parser/AlgoBaseUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/CloseDetailsTabUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/DeletePlanUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/DeleteProblemUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/EditPlanUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/EditProblemUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/OpenDetailsTabUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/SetPlanUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/SwitchDetailsTabUiActionParser.java
  src/main/java/seedu/algobase/ui/action/parser/SwitchDisplayTabUiActionParser.java
Labels: status.reviewRequired, type.Bug

#214 implement tagcolor features
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/tag/AddTagSequenceDiagram.puml
  docs/diagrams/tag/TagActivityDiagram.puml
  docs/diagrams/tag/TagClassDirgram.puml
  docs/images/tag/TagActivityDiagram.png
  docs/images/tag/TagClassDiagram.png
  docs/images/tag/TagCommandActivityDiagram.png
  src/main/java/seedu/algobase/logic/commands/Command.java
  src/main/java/seedu/algobase/logic/commands/problem/AddCommand.java
  src/main/java/seedu/algobase/logic/commands/problem/EditCommand.java
  src/main/java/seedu/algobase/logic/commands/tag/AddTagCommand.java
  src/main/java/seedu/algobase/logic/commands/tag/EditTagColorCommand.java
  src/main/java/seedu/algobase/logic/commands/tag/EditTagCommand.java
  src/main/java/seedu/algobase/logic/parser/AlgoBaseParser.java
  src/main/java/seedu/algobase/logic/parser/CliSyntax.java
  src/main/java/seedu/algobase/logic/parser/ParserUtil.java
  src/main/java/seedu/algobase/logic/parser/tag/AddTagCommandParser.java
  src/main/java/seedu/algobase/logic/parser/tag/DeleteTagCommandParser.java
  src/main/java/seedu/algobase/logic/parser/tag/EditTagColorCommandParser.java
  src/main/java/seedu/algobase/logic/parser/tag/EditTagCommandParser.java
  src/main/java/seedu/algobase/model/ModelManager.java
  src/main/java/seedu/algobase/model/tag/Tag.java
  src/main/java/seedu/algobase/storage/JsonAdaptedTag.java
  src/main/java/seedu/algobase/ui/ProblemCard.java
  src/main/java/seedu/algobase/ui/TagCard.java
  src/main/java/seedu/algobase/ui/TaskCard.java
  src/test/java/seedu/algobase/integration/AddFindRuleCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/AddPlanCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/AddTagCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/EditPlanCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/EditProblemCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/EditTagCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/HelpCommandIntegrationTest.java
  src/test/java/seedu/algobase/logic/commands/HelpCommandTest.java
Labels: status.reviewRequired

#238 DG error
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/design/model/PlanPackageDiagram.puml
  docs/diagrams/design/model/PlanSearchRulePackageDiagram.puml
  docs/diagrams/design/model/TaskPackageDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/images/design/model/PlanPackageDiagram.png
  docs/images/design/model/PlanSearchRulePackageDiagram.png
  docs/images/design/model/TaskPackageDiagram.png
  docs/team/seris370.adoc
Labels: status.reviewRequired

#239 Handle Storage exceptions for GuiState and Manual Tests
  docs/DeveloperGuide.adoc
  src/main/java/seedu/algobase/MainApp.java
  src/main/java/seedu/algobase/storage/JsonAdaptedGuiState.java
  src/main/java/seedu/algobase/storage/JsonAdaptedTabManager.java
  src/main/java/seedu/algobase/storage/JsonSerializableAlgoBase.java
  src/main/java/seedu/algobase/ui/MainWindow.java
  src/main/java/seedu/algobase/ui/action/UiActionResult.java
  src/main/java/seedu/algobase/ui/action/actions/CloseDetailsTabUiAction.java
  src/main/java/seedu/algobase/ui/action/actions/DeletePlanUiAction.java
  src/main/java/seedu/algobase/ui/action/actions/DeleteProblemUiAction.java
  src/main/java/seedu/algobase/ui/action/actions/EditPlanUiAction.java
  src/main/java/seedu/algobase/ui/action/actions/EditProblemUiAction.java
  src/main/java/seedu/algobase/ui/action/actions/OpenDetailsTabUiAction.java
  src/main/java/seedu/algobase/ui/action/actions/SetPlanUiAction.java
  src/main/java/seedu/algobase/ui/action/actions/SwitchDetailsTabUiAction.java
  src/main/java/seedu/algobase/ui/action/actions/SwitchDisplayTabUiAction.java
  src/main/java/seedu/algobase/ui/details/PlanDetails.java
  src/main/java/seedu/algobase/ui/details/ProblemDetails.java
  src/main/resources/view/PlanDetails.fxml
  src/main/resources/view/ProblemDetails.fxml
Labels: status.reviewRequired

#243 Fix PPP bug
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/design/model/ModelClassDiagram.puml
  docs/diagrams/design/model/PlanSearchRulePackageDiagram.puml
  docs/diagrams/design/model/ProblemSearchRulePackageDiagram.puml
  docs/diagrams/savefindrule/AddFindRuleClassDiagram.puml
  docs/diagrams/savefindrule/AddFindRuleSequenceDiagram.puml
  docs/images/design/model/ModelClassDiagram.png
  docs/images/design/model/PlanSearchRulePackageDiagram.png
  docs/images/design/model/ProblemSearchRulePackageDiagram.png
  docs/images/savefindrule/AddFindRuleClassDiagram.png
  docs/images/savefindrule/AddFindRuleSequenceDiagram.png
  docs/team/le0tan.adoc
Labels: status.reviewRequired

#245 Minor PPP changes
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/stylesheets/asciidoctor.css
  docs/team/tiuweehan.adoc
Labels: status.reviewRequired

#250 Fix find rule name regex bug
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/Name.java
  src/test/java/seedu/algobase/model/searchrule/problemsearchrule/NameTest.java
  src/test/java/seedu/algobase/storage/JsonAdaptedProblemSearchRuleTest.java
Labels: status.reviewRequired

#242 Documentation Revision and Bugs fixed
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  src/main/java/seedu/algobase/logic/commands/EditPlanCommand.java
  src/main/java/seedu/algobase/logic/commands/FindPlanCommand.java
  src/main/java/seedu/algobase/logic/parser/EditPlanCommandParser.java
  src/test/java/seedu/algobase/integration/AddPlanCommandIntegrationTest.java
  src/test/java/seedu/algobase/integration/EditPlanCommandIntegrationTest.java
Labels: status.reviewRequired

#256 Update documentation
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UiDisplayTabClassDiagram.puml
  docs/diagrams/storage/ProblemSearchRuleClassDiagram.puml
  docs/diagrams/tag/TagClassDiagram.puml
  docs/diagrams/task/AddTaskSequenceDiagram.puml
  docs/diagrams/task/HighLevelAddTaskSequenceDiagram.puml
  docs/diagrams/task/HighLevelTaskClassDiagram.puml
  docs/diagrams/task/TaskClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/Ui.png
  docs/images/UiClassDiagram.png
  docs/images/UiDisplayTabClassDiagram.png
  docs/images/UiStartPlan.png
  docs/images/storage/ProblemSearchRuleClassDiagram.png
  docs/images/task/AddTaskSequenceDiagram.png
  docs/images/task/HighLevelAddTaskSequenceDiagram.png
  docs/images/task/HighLevelTaskClassDiagram.png
  docs/images/task/TaskClassDiagram.png
  docs/team/jiayushe.adoc
  src/main/java/seedu/algobase/logic/Logic.java
  src/main/java/seedu/algobase/logic/LogicManager.java
  src/main/java/seedu/algobase/logic/commands/EditPlanCommand.java
  src/main/java/seedu/algobase/logic/commands/task/AddTaskCommand.java
  src/main/java/seedu/algobase/logic/commands/task/EditTaskCommand.java
  src/main/java/seedu/algobase/logic/commands/task/TaskCommandUtil.java
  src/main/java/seedu/algobase/logic/parser/task/AddTaskCommandParser.java
  src/main/java/seedu/algobase/logic/parser/task/CopyTaskCommandParser.java
  src/main/java/seedu/algobase/logic/parser/task/DeleteTaskCommandParser.java
  src/main/java/seedu/algobase/logic/parser/task/DoneTaskCommandParser.java
  src/main/java/seedu/algobase/logic/parser/task/EditTaskCommandParser.java
  src/main/java/seedu/algobase/logic/parser/task/MoveTaskCommandParser.java
  src/main/java/seedu/algobase/logic/parser/task/SetPlanCommandParser.java
  src/main/java/seedu/algobase/logic/parser/task/UndoneTaskCommandParser.java
  src/main/java/seedu/algobase/model/AlgoBase.java
  src/main/java/seedu/algobase/model/Model.java
  src/main/java/seedu/algobase/model/ModelManager.java
  src/main/java/seedu/algobase/model/ReadOnlyAlgoBase.java
  src/main/java/seedu/algobase/model/plan/Plan.java
  src/main/java/seedu/algobase/model/plan/PlanList.java
  src/main/java/seedu/algobase/model/plan/PlanName.java
  src/main/java/seedu/algobase/model/problem/Name.java
  src/main/java/seedu/algobase/model/searchrule/problemsearchrule/Name.java
  src/main/java/seedu/algobase/model/task/Task.java
  src/main/java/seedu/algobase/storage/JsonAdaptedTask.java
  src/main/java/seedu/algobase/ui/MainWindow.java
  src/main/java/seedu/algobase/ui/ProblemCard.java
  src/main/java/seedu/algobase/ui/TaskCard.java
  src/main/java/seedu/algobase/ui/TaskManagementPane.java
  src/main/resources/view/TaskListCard.fxml
  src/test/java/seedu/algobase/integration/AddProblemCommandIntegrationTest.java
  src/test/java/seedu/algobase/logic/commands/DefaultModelStub.java
  src/test/java/seedu/algobase/model/problem/NameTest.java
  src/test/java/seedu/algobase/model/searchrule/problemsearchrule/NameTest.java
  src/test/java/seedu/algobase/model/task/TaskTest.java
  src/test/java/seedu/algobase/testutil/TaskBuilder.java
Labels: status.reviewRequired

#257 Minor fix for Documentation
  docs/DeveloperGuide.adoc
  docs/diagrams/task/TaskClassDiagram.puml
Labels: status.reviewRequired

#263 Remove manual test cases
  docs/DeveloperGuide.adoc
Labels: status.reviewRequired

#264 Standardize formatting
  docs/DeveloperGuide.adoc
  docs/images/findprob_1.png
  docs/images/gui/DeleteProblemUiAction0.png
  docs/images/gui/DeleteProblemUiAction0Annotated.png
  docs/images/gui/DeleteProblemUiAction1.png
  docs/images/gui/DeleteProblemUiAction1Annotated.png
  docs/images/gui/DeleteProblemUiAction2.png
  docs/images/gui/DeleteProblemUiAction2Annotated.png
  docs/images/gui/EditPlanUiAction0.png
  docs/images/gui/EditPlanUiAction0Annotated.png
  docs/images/gui/EditPlanUiAction1Annotated.png
  docs/images/gui/EditPlanUiAction2Annotated.png
  docs/images/gui/OpenTabCommand.png
  docs/images/gui/SwitchTabCommand.png
  docs/images/gui/TabsOverview1.png
  src/main/java/seedu/algobase/commons/core/Messages.java
Labels: status.reviewRequired
